### Model Section (模型参数)
# 基座模型路径 (必填)
model_name_or_path: "Qwen/Qwen2.5-0.5B-Instruct"
model_cache: /mnt/share/wwt/models/Qwen/Qwen2.5-0.5B-Instruct  # 模型缓存目录, 例如: "saves/models"
# LoRA 权重路径
adapter_name_or_path: null  # 例如: "saves/qwen2.5-0.5B-Instruct/lora/sft"
# Embedding 模型
embedding_name_or_path: "Qwen/Qwen3-Embedding-0.6B"
embedding_cache: /mnt/share/wwt/models/Qwen/Qwen3-Embedding-0.6B
embed_batch_size: 32

### Dataset Section (数据与评估)
# 测试集路径
dataset_path: "model_eval/sample_sft_test.json"
# 截断长度
cutoff_len: 3072

### Output Section (结果输出)
# 结果输出目录
output_dir: "eval_outputs/qwen2.5-0.5B-Instruct/pretrained"
# 运行 ID (用于文件名)
run_label: "semantic_eval"

### Metric Section (指标逻辑)
# 相似度阈值
threshold: 0.5